<?php

namespace AMUH\AmuhBundle\Repository;

/**
 * AttributRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAttributsByCategorieId($idCategorieAttribut){
		$queryBuilder = $this->createQueryBuilder('atb')
			->where('atb.categorieAttribut= :idCategorieAttribut')
			->setParameter('idCategorieAttribut', $idCategorieAttribut);
			
		return $queryBuilder->getQuery()->getResult();
	}
}
