<?php

namespace AMUH\AmuhBundle\Repository;

/**
 * CategorieAttributRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieAttributRepository extends \Doctrine\ORM\EntityRepository
{
}
