<?php

namespace AMUH\AmuhBundle\Repository;

/**
 * JourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJourneeOrderByByDateOrderByConsultationDateHeure($date){
        $dateFormat = \DateTime::createFromFormat('d/m/Y', $date);
        
        $queryBuilder = $this
                ->createQueryBuilder('jou')
                ->innerJoin('jou.medecins', 'med')
                ->addSelect('med')
                ->innerJoin('jou.secretaires', 'sec')
                ->addSelect('sec')
                ->innerJoin('jou.consultations', 'con')
                ->addSelect('con')
                ->where('jou.jouDate = :date')
                ->setParameter(':date', $dateFormat->format('Y-m-d'))
                ->orderBy('con.cstDateCreation');
        
        return $queryBuilder->getQuery()->getResult();
    }
}
