<?php

namespace AMUH\AmuhBundle\Repository;

/**
 * ModaliteReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModaliteReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
