<?php

namespace AMUH\AmuhBundle\Repository;

/**
 * TypeJourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeJourneeRepository extends \Doctrine\ORM\EntityRepository
{
}
